### ISSUE TITLE
Missing parameters in file replay_analyser.py, function cache_players_from_replays

### ISSUE THREAD

**Issue by ootjersb** [Baldrickk/replay_team_balance#1]
Hi Baldrickk,

Could find out how to create a branch and push the changes back or via pull request...
But these are some minor problems in the file right now:

Line 210 should be:
def cache_players_from_replays(directory, application_id):

Line 229 should be:
cache_players_from_replays(directory, application_id)

Regards,
forkboy1 (in WoT)

**Comment by ootjersb** [comment]
There is another problem in returning the teams variable, since that became local to the function cache_players_from_replays as well... did not fix that, returned to previous version since my Python skills are lacking currently

**Comment by Baldrickk** [comment]
Ah. Yes. That was an accidental change. I was doing dine refactoring, didn't finish, then pushed it with some other changes.
Should be fixed now (2 days ago). Sorry I didn't see this until then.
