### ISSUE TITLE
Percentage difference calculation is not correct

### ISSUE THREAD

**Issue by ootjersb** [Baldrickk/replay_team_balance#6]
The percentage difference calculation always takes the green team as base. This leads to an error in calculating the difference in strength between the teams.

Example:
green team rating: 10
red team rating: 15
diff = 100*(10-15)/10 = -50%

red team rating: 15
green team rating: 10
diff = 100*(15-10)/15 = 33.33%

I would say that for teams the difference is the same, it is only reversed.

Therefore I changed the logic like this:
```python
def percent_diff(a, b):
    base = b
    if a < b:
        base = a
    return 100*(float(a)-float(b))/float(base)
```

**Comment by Baldrickk** [comment]
This isn't a bug
I knocked up a quick demo: https://ideone.com/OmCJm5

Note that the sign is "the wrong way" - this is intended, although it is not obvious why;  The magnitude is the percentage difference between the two teams, relative to the team the player is on.  The sign is positive if the players team was better.  This leads to the graph being the right way round.

I could choose to switch the base around, and compare the players team to the opposition team.  This would be:
```python
def opposite(a, b):
    return 100*(float(b)-float(a))/float(b)
```
and can be seen in the output of the demo above, but I made the design decision to make it relative to the player's team.  The results are more meaningful then.

Your proposed change is inconsistant.  Both the `current` and `opposite` methods are correct, they just show slightly different things.  Your code switches between them, and loses that consistency.  In one comparison, you are comparing team a to team b, and in the next, team b to team a.

If you have three students, one who scores 50%, one who scores 40% and one who scores 60% in a test.
the second and third have scored, respectively, 20% lower, and 20% higher than the first.
We don't say that the second scored 20% lower than the first, and the first 16.66% lower than the third, and use those percentages to compare the students.
